import { SITE_CONFIG } from "@/lib/config";

export type GearItem = {
  slug: string;
  name: string;
  category: string;
  priority: "Buy first" | "Worth it" | "Nice to have";
  recommendation: string;
  affiliateUrl: string;
  linkLabel: string;
  notes: string;
  tags: string[];
};

function amazonProduct(path: string) {
  const separator = path.includes("?") ? "&" : "?";
  return `https://www.amazon.com${path}${separator}tag=${SITE_CONFIG.amazonTag}`;
}

export const GEAR_ITEMS: GearItem[] = [
  { slug: "chickenguard-one-automatic-coop-door", name: "ChickenGuard One Automatic Chicken Coop Door Opener", category: "Chicken coop", priority: "Buy first", recommendation: "Automatic doors are one of the first upgrades we recommend because they protect morning/evening rhythms and reduce chore failure points.", affiliateUrl: amazonProduct("/ChickenGuard-Automatic-Auto-Stop-Predator-Batteries-Compatible/dp/B0BZ8PHPPR"), linkLabel: "Check ChickenGuard One on Amazon", notes: "Verify coop opening size, power option, and cold-weather behavior during the return window.", tags: ["chickens", "automation", "predator-protection", "coop"] },
  { slug: "premier-1-poultrynet-plus-starter-kit", name: "Premier 1 PoultryNet Plus Starter Kit, 48 in x 100 ft", category: "Fencing & pasture", priority: "Buy first", recommendation: "Portable poultry netting is the easiest way to move birds onto fresh grass while keeping most ground predators honest.", affiliateUrl: amazonProduct("/Premier-PoultryNet-Plus-Starter-Kit/dp/B071J99Q19"), linkLabel: "Check Premier 1 PoultryNet kit on Amazon", notes: "Measure the run first. Extra support posts matter on uneven ground more than the product photo suggests.", tags: ["chickens", "pasture", "fencing", "predators"] },
  { slug: "premier-1-chick-brooder-heating-plate", name: "Premier 1 Chick Brooder Heating Plate, 12 x 12 in", category: "Brooding", priority: "Buy first", recommendation: "A brooder plate is calmer and more efficient than a heat lamp for many small chick batches, and it reduces fire-risk anxiety.", affiliateUrl: amazonProduct("/Premier-Chick-Brooder-Heating-Plate/dp/B00W43PHTA"), linkLabel: "Check Premier 1 brooder plate on Amazon", notes: "Size the plate to your chick count and keep one backup heat plan if your brooder is in a cold garage or outbuilding.", tags: ["chicks", "brooder", "poultry", "starter-gear"] },
  { slug: "harris-farms-15-pound-galvanized-poultry-feeder", name: "Harris Farms 15 lb Galvanized Hanging Poultry Feeder", category: "Feeding & watering", priority: "Worth it", recommendation: "A hanging metal feeder keeps feed cleaner than ground bowls and saves the daily drama of chickens turning breakfast into confetti.", affiliateUrl: amazonProduct("/Harris-Farms-1000293-Galvanized-Hanging/dp/B006ZUNIR6"), linkLabel: "Check Harris Farms feeder on Amazon", notes: "Hang it at back height. Too low wastes feed; too high turns dinner into chicken CrossFit.", tags: ["chickens", "feed", "coop", "daily-chores"] },
  { slug: "harris-farms-5-gallon-galvanized-poultry-drinker", name: "Harris Farms 5 Gallon Double Wall Galvanized Poultry Drinker", category: "Feeding & watering", priority: "Worth it", recommendation: "A larger drinker is boring in the best possible way: fewer refills, steadier water access, and less chore friction.", affiliateUrl: amazonProduct("/Harris-Farms-Galvanized-Poultry-Drinker/dp/B006ZJHBPM"), linkLabel: "Check Harris Farms drinker on Amazon", notes: "Set it level and test for leaks before trusting it for a long day away from home.", tags: ["chickens", "water", "coop", "daily-chores"] },
  { slug: "presto-01781-23-quart-pressure-canner", name: "Presto 01781 23-Quart Pressure Canner and Cooker", category: "Food preservation", priority: "Buy first", recommendation: "For vegetables, stock, meat, and shelf-stable pantry work, a real pressure canner is non-negotiable gear.", affiliateUrl: amazonProduct("/Presto-01781-23-Quart-Pressure-Canner/dp/B0000BYCFU"), linkLabel: "Check Presto 23 qt pressure canner on Amazon", notes: "Confirm stove compatibility, read the manual, and follow tested canning recipes. Food safety is not kitchen jazz improv.", tags: ["canning", "food-preservation", "pantry", "garden"] },
  { slug: "all-american-921-pressure-canner", name: "All American 1930 21.5 qt Pressure Cooker/Canner (921)", category: "Food preservation", priority: "Worth it", recommendation: "This is the upgrade pick for families who preserve a lot and want a gasket-free canner that feels like farm equipment, not a toy pot.", affiliateUrl: amazonProduct("/All-American-21-5qt-Pressure-Cooker/dp/B0BSMM1V6G"), linkLabel: "Check All American 921 on Amazon", notes: "It is heavy. Make sure your stove and storage setup can handle it before buying like a pioneer with Prime shipping.", tags: ["canning", "food-preservation", "upgrade", "pantry"] },
  { slug: "ball-mason-jar-canning-starter-kit", name: "Ball Glass Mason Jar Canning Starter Kit", category: "Food preservation", priority: "Buy first", recommendation: "New canners need basic jars, lids, bands, and safe handling tools before they need fancy pantry labels.", affiliateUrl: amazonProduct("/Ball-Canning-Starter-Regular-Dissolvable/dp/B0DJC8PB5P"), linkLabel: "Check Ball starter kit on Amazon", notes: "Use new lids for canning. Reused lids are fine for dry storage, not for sealed food you plan to trust in January.", tags: ["canning", "jars", "food-preservation", "starter-gear"] },
  { slug: "excalibur-3548cdb-food-dehydrator", name: "Excalibur 3548CDB Electric Food Dehydrator", category: "Food preservation", priority: "Nice to have", recommendation: "A dehydrator turns extra herbs, fruit, and garden overflow into shelf-stable wins without needing freezer space.", affiliateUrl: amazonProduct("/Excalibur-3548CDB-Dehydrator-Adjustable-Thermostat/dp/B071XV6FV2"), linkLabel: "Check Excalibur dehydrator on Amazon", notes: "Buy this when you already know what you will dry. Aspirational dehydrators become expensive basement sculptures.", tags: ["dehydrating", "food-preservation", "garden", "pantry"] },
  { slug: "lodge-6-quart-enameled-dutch-oven", name: "Lodge 6 Quart Enameled Cast Iron Dutch Oven", category: "Outdoor cooking", priority: "Worth it", recommendation: "A sturdy Dutch oven works for soups, roasts, bread, and the kind of farm-day meals where everyone is hungry at once.", affiliateUrl: amazonProduct("/Lodge-Quart-Enameled-Dutch-Enamel/dp/B000N4WN08"), linkLabel: "Check Lodge Dutch oven on Amazon", notes: "For open-fire cooking, choose a camp Dutch oven instead. Enameled cast iron is kitchen gear, not campfire armor.", tags: ["cast-iron", "cooking", "kitchen", "family-meals"] },
  { slug: "thermopro-tp20-wireless-meat-thermometer", name: "ThermoPro TP20 Wireless Meat Thermometer", category: "Outdoor cooking", priority: "Worth it", recommendation: "A probe thermometer keeps grilling, smoking, and roasting from becoming guesswork with a side of regret.", affiliateUrl: amazonProduct("/ThermoPro-Wireless-Digital-Cooking-Thermometer/dp/B01GE77QT0"), linkLabel: "Check ThermoPro TP20 on Amazon", notes: "Test probe accuracy in ice water and boiling water during the return window. Trust, but verify.", tags: ["meat", "grilling", "cooking", "thermometer"] },
  { slug: "wisephone-family-safe-phone", name: "Wisephone Family-Safe Phone", category: "Family tech", priority: "Worth it", recommendation: "Wisephone is for families who want phone utility without handing a child the entire internet in their pocket.", affiliateUrl: SITE_CONFIG.wisephoneDiscountUrl, linkLabel: "See Wisephone discount", notes: "Use the discount link and compare the monthly plan against your current carrier before switching.", tags: ["family-tech", "phones", "kids", "digital-discipleship"] },
  { slug: "covenant-eyes-accountability", name: "Covenant Eyes Internet Accountability", category: "Family tech", priority: "Worth it", recommendation: "Covenant Eyes is a practical accountability layer for families trying to build honest digital habits without pretending temptation is theoretical.", affiliateUrl: SITE_CONFIG.covenantEyesUrl, linkLabel: "See Covenant Eyes", notes: "Pair it with family conversations and device rules. Software helps, but it is not a substitute for discipleship.", tags: ["family-tech", "accountability", "internet-safety", "digital-discipleship"] },
];
